# Generated by Django 2.2.7 on 2019-11-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='Course_Materials',
            new_name='asdrse_Materials',
        ),
    ]
