# Generated by Django 2.2.7 on 2019-11-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0002_auto_20191111_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='asdrse_Materials',
        ),
    ]
