# Generated by Django 2.2.7 on 2019-11-11 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0005_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
