# Generated by Django 2.2.7 on 2019-11-11 23:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0006_announcement_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 23, 35, 43, 947028, tzinfo=utc)),
        ),
    ]
