# Generated by Django 2.2.7 on 2019-11-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0008_auto_20191112_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='isAssistant',
            field=models.BooleanField(default=False, verbose_name='Assistant'),
        ),
        migrations.AlterField(
            model_name='role',
            name='isInstructor',
            field=models.BooleanField(default=False, verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='role',
            name='isStudent',
            field=models.BooleanField(default=False, verbose_name='Student'),
        ),
    ]
