# Generated by Django 2.2.7 on 2019-11-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0010_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
