# Generated by Django 2.2.7 on 2019-12-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0015_auto_20191205_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='period',
            field=models.CharField(default='guz2018', max_length=10),
            preserve_default=False,
        ),
    ]
