# Generated by Django 2.2.7 on 2019-12-18 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0016_lecture_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='isAssistant',
        ),
        migrations.RemoveField(
            model_name='role',
            name='isInstructor',
        ),
        migrations.RemoveField(
            model_name='role',
            name='isStudent',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='instructor_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('name', 'period')},
        ),
    ]
