# Generated by Django 3.0.1 on 2019-12-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0017_auto_20191218_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
