# Generated by Django 3.0.1 on 2019-12-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0018_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='docfile',
            new_name='doc_file',
        ),
    ]
