# Generated by Django 2.2.7 on 2020-01-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0021_auto_20200104_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='doc_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
