# Generated by Django 2.2.7 on 2020-01-04 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0022_auto_20200105_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursematerial',
            name='doc_file',
        ),
        migrations.CreateModel(
            name='CourseMaterialFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('doc_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainProject.CourseMaterial')),
            ],
        ),
    ]
