# Generated by Django 2.2.7 on 2020-01-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0023_auto_20200105_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='doc_file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.DeleteModel(
            name='CourseMaterialFile',
        ),
    ]
