# Generated by Django 2.2.7 on 2020-01-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0025_auto_20200105_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursematerial',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
