# Generated by Django 2.2.7 on 2020-01-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0026_auto_20200105_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentuploadfile',
            name='doc_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
