# Generated by Django 2.2.7 on 2020-01-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0028_auto_20200107_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='coursematerial',
            options={'verbose_name': 'CourseMaterial', 'verbose_name_plural': 'CourseMaterials'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': 'Lecture', 'verbose_name_plural': 'Lectures'},
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together=set(),
        ),
    ]
