# Generated by Django 3.0.1 on 2020-01-09 10:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0031_auto_20200109_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
