# Generated by Django 3.0.1 on 2020-01-09 11:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0032_auto_20200109_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='doc_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
