# Generated by Django 3.0.1 on 2020-01-11 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainProject', '0037_auto_20200109_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='syllabus',
        ),
        migrations.AlterField(
            model_name='studentuploadfile',
            name='doc_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('doc_file', models.FileField(null=True, upload_to='')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='MainProject.Lecture')),
            ],
        ),
    ]
