# Generated by Django 2.2.7 on 2020-01-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0038_auto_20200111_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='given_class',
            field=models.ManyToManyField(related_name='givenByInstructor', to='MainProject.Lecture'),
        ),
    ]
