# Generated by Django 2.2.7 on 2020-01-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainProject', '0039_auto_20200113_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='given_class',
            field=models.ManyToManyField(to='MainProject.Lecture'),
        ),
    ]
